spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

#for spring-actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

# Info Details for Cards Application in Service Registry
info:
  app:
    name: "gatewayserver"
    description: "Gateway Server Application"
    version: "1.0.0"
